version: "3.9"

services:

  mysql:
    image: mysql:8.0
    container_name: profroid-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: profroid
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - profroid-net

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: profroid-phpmyadmin
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - profroid-net

  monolith:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: profroid-app
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/profroid
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    networks:
      - profroid-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: profroid-frontend
    restart: always
    depends_on:
      - monolith
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - profroid-net

volumes:
  mysql_data:

networks:
  profroid-net:
